export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CHECKAUTH_REQUEST = "CHECKAUTH_REQUEST";
export const CHECKAUTH_SUCCESS = "CHECKAUTH_SUCCESS";
export const CHECKAUTH_FAILURE = "CHECKAUTH_FAILURE";

export const CHECK_USER_EXISTENCE_REQUEST = "CHECKAUTH_REQUEST";
export const CHECK_USER_EXISTENCE_SUCCESS = "CHECKAUTH_SUCCESS";
export const CHECK_USER_EXISTENCE_FAILURE = "CHECKAUTH_FAILURE";

export const EDIT_REQUEST = "EDIT_REQUEST";
export const EDIT_SUCCESS = "EDIT_SUCCESS";
export const EDIT_FAILURE = "EDIT_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const ADMIN_REQUEST = "ADMIN_REQUEST";
export const ADMIN_SUCCESS = "ADMIN_SUCCESS";
export const ADMIN_FAILURE = "ADMIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const ACTIVATE_REQUEST = "ACTIVATE_REQUEST";
export const ACTIVATE_SUCCESS = "ACTIVATE_SUCCESS";
export const ACTIVATE_FAILURE = "ACTIVATE_FAILURE";

export const CHECK_EMAIL_REQUEST = "CHECK_EMAIL_REQUEST";
export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS";
export const CHECK_EMAIL_FAILURE = "CHECK_EMAIL_FAILURE";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const SEND_CONTACTS_SUCCESS = "SEND_CONTACTS_SUCCESS";
export const SEND_CONTACTS_FAILURE = "SEND_CONTACTS_FAILURE";

export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_FAILURE = "LOGIN_ADMIN_FAILURE";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";
export const EDIT_AVATAR_SUCCESS = "EDIT_AVATAR_SUCCESS";
export const GET_SUCCESS_REVIEWS = "GET_SUCCESS_REVIEWS";
export const USER_BY_ID_SUCCESS = "USER_BY_ID_SUCCESS";
export const EDIT_UPLOAD_ID_SUCCESS = "EDIT_UPLOAD_ID_SUCCESS";
export const ERROR_SAVE_USER = "ERROR_SAVE_USER";
//Loading
export const LOADING = "LOADING";

//SignUp Admin
export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS";
export const ADMIN_SIGNUP_FAILURE = "ADMIN_SIGNUP_FAILURE";
export const GET_ADMIN_ROLES = "GET_ADMIN_ROLES";

//Verify Approval
export const APPROVAL_SUCCESS = "APPROVAL_SUCCESS";
export const APPROVAL_FAILURE = "APPROVAL_FAILURE";

export const GET_REFERRAL_USAGES_SUCCESS = "GET_REFERRAL_USAGES_SUCCESS";
export const GET_REFERRAL_USAGES_FAILURE = "GET_REFERRAL_USAGES_FAILURE";

export const VERIFY_MODAL_PHONE = "VERIFY_MODAL_PHONE";

export const CHECK_PHONE_SUCCESS = "CHECK_PHONE_SUCCESS";
export const CHECK_PHONE_FAIL = "CHECK_PHONE_FAIL";

export const SET_URL = "SET_URL";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";

export const GET_CURRENT_CHAT_SUCCESS = "GET_CURRENT_CHAT_SUCCESS";
export const GET_CHATTING_USERS_SUCCESS = "GET_CHATTING_USERS_SUCCESS";
export const SEND_CURRENT_MESSAGE_SUCCESS = "SEND_CURRENT_MESSAGE_SUCCESS";

export const SET_VALID_SUCCESS = "SET_VALID_SUCCESS";
export const VERIFY_PHONE_SUCCESS = "VERIFY_PHONE_SUCCESS";
