export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAILURE = "GET_REVIEWS_FAILURE";

export const GET_MORE_REVIEWS_REQUEST = "GET_MORE_REVIEWS_REQUEST";
export const GET_MORE_REVIEWS_SUCCESS = "GET_MORE_REVIEWS_SUCCESS";
export const GET_MORE_REVIEWS_FAILURE = "GET_MORE_REVIEWS_FAILURE";

export const CLEANUP_MORE_REVIEWS = "CLEANUP_MORE_REVIEWS";
export const ADD_REVIEW_FOR_VENUE_SUCCESS = "ADD_REVIEW_FOR_VENUE_SUCCESS";
export const ADD_REVIEW_FOR_VENUE_FAILURE = "ADD_REVIEW_FOR_VENUE_FAILURE";

export const ADD_REVIEW_FOR_BUILDING_SUCCESS =
  "ADD_REVIEW_FOR_BUILDING_SUCCESS";
export const ADD_REVIEW_FOR_BUILDING_FAILURE =
  "ADD_REVIEW_FFOR_BUILDING_AILURE";

export const ADD_REVIEW_FOR_USER_SUCCESS = "ADD_REVIEW_FOR_USER_SUCCESS";
export const ADD_REVIEW_FOR_USER_FAILURE = "ADD_REVIEW_FFOR_USER_AILURE";

// export const ADD_IMAGE_FOR_BUILDING_REVIEW_REQUEST = 'ADD_IMAGE_FOR_BUILDING_REVIEW_REQUEST';
// export const ADD_IMAGE_FOR_BUILDING_REVIEW_SUCCES = 'ADD_IMAGE_FOR_BUILDING_REVIEW_SUCCES';
// export const ADD_IMAGE_FOR_BUILDING_REVIEW_FAILURE = 'ADD_IMAGE_FOR_BUILDING_REVIEW_FAILURE';

// export const ADD_VIDEO_FOR_BUILDING_REVIEW_REQUEST = 'ADD_VIDEO_FOR_BUILDING_REVIEW_REQUEST';
// export const ADD_VIDEO_FOR_BUILDING_REVIEW_SUCCES = 'ADD_VIDEO_FOR_BUILDING_REVIEW_SUCCES';
// export const ADD_VIDEO_FOR_BUILDING_REVIEW_FAILURE = 'ADD_VIDEO_FOR_BUILDING_REVIEW_FAILURE';
export const ADD_MEDIA_FOR_BUILDING_REVIEW_REQUEST =
  "ADD_MEDIA_FOR_BUILDING_REVIEW_REQUEST";
export const ADD_MEDIA_FOR_BUILDING_REVIEW_SUCCES =
  "ADD_MEDIA_FOR_BUILDING_REVIEW_SUCCES";
export const ADD_MEDIA_FOR_BUILDING_REVIEW_FAILURE =
  "ADD_MEDIA_FOR_BUILDING_REVIEW_FAILURE";
