export const CREATE_PLACE_REQUEST = "CREATE_PLACE_REQUEST";
export const CREATE_PLACE_SUCCESS = "CREATE_PLACE_SUCCESS";
export const CREATE_PLACE_FAILURE = "CREATE_PLACE_FAILURE";

export const GET_SIMILAR_PLACE_REQUEST = "GET_SIMILAR_PLACE_REQUEST";
export const GET_SIMILAR_PLACE_SUCCESS = "GET_SIMILAR_PLACE_SUCCESS";
export const GET_SIMILAR_PLACE_FAILURE = "GET_SIMILAR_PLACE_FAILURE";

export const CREATE_LATEST_EXC_RATE_FAILURE = "CREATE_LATEST_EXC_RATE_FAILURE";
export const CREATE_LATEST_EXC_RATE_SUCCESS = "CREATE_LATEST_EXC_RATE_SUCCESS";

export const GET_PLACE_REQUEST = "GET_PLACE_REQUEST";
export const GET_PLACE_SUCCESS = "GET_PLACE_SUCCESS";
export const GET_PLACE_FAILURE = "GET_PLACE_FAILURE";

export const GET_RATED_PLACES_SUCCESS = "GET_RATED_PLACES_SUCCESS";
export const GET_RATED_PLACES_FAILURE = "GET_RATED_PLACES_FAILURE";

export const GET_LAST_PLACES_SUCCESS = "GET_LAST_PLACES_SUCCESS";
export const GET_LAST_PLACES_FAILURE = "GET_LAST_PLACES_FAILURE";

export const GET_PLACE_DETAILS_REQUEST = "GET_PLACE_DETAILS_REQUEST";
export const GET_PLACE_DETAILS_SUCCESS = "GET_PLACE_DETAILS_SUCCESS";
export const GET_PLACE_DETAILS_FAILURE = "GET_PLACE_DETAILS_FAILURE";

export const EDIT_PLACE_REQUEST = "EDIT_PLACE_REQUEST";
export const EDIT_PLACE_SUCCESS = "EDIT_PLACE_SUCCESS";
export const EDIT_PLACE_FAILURE = "EDIT_PLACE_FAILURE";

export const DELETE_PLACE_REQUEST = "DELETE_PLACE_REQUEST";
export const DELETE_PLACE_SUCCESS = "DELETE_PLACE_SUCCESS";
export const DELETE_PLACE_FAILURE = "DELETE_PLACE_FAILURE";

export const UPLOAD_FILES_REQUEST = "UPLOAD_FILES_REQUEST";
export const UPLOAD_FILES_SUCCESS = "UPLOAD_FILES_SUCCESS";
export const UPLOAD_FILES_FAILURE = "UPLOAD_FILES_FAILURE";

export const GET_CITIES_REQUEST = "GET_CITIES_REQUEST";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";
export const GET_CITIES_FAILURE = "GET_CITIES_FAILURE";
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";

export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export const GET_FAVORITE_BUILDING_REQUEST = "GET_FAVORITE_BUILDING_REQUEST";
export const GET_FAVORITE_BUILDING_SUCCESS = "GET_FAVORITE_BUILDING_SUCCESS";
export const GET_FAVORITE_BUILDING_FAILURE = "GET_FAVORITE_BUILDING_FAILURE";

export const ADD_FAVORITE_BUILDING_REQUEST = "ADD_FAVORITE_BUILDING_REQUEST";
export const ADD_FAVORITE_BUILDING_SUCCESS = "ADD_FAVORITE_BUILDING_SUCCESS";
export const ADD_FAVORITE_BUILDING_FAILURE = "ADD_FAVORITE_BUILDING_FAILURE";

export const REMOVE_FAVORITE_BUILDING_REQUEST =
  "REMOVE_FAVORITE_BUILDING_REQUEST";
export const REMOVE_FAVORITE_BUILDING_SUCCESS =
  "REMOVE_FAVORITE_BUILDING_SUCCESS";
export const REMOVE_FAVORITE_BUILDING_FAILURE =
  "REMOVE_FAVORITE_BUILDING_FAILURE";

export const SEARCH_CITY_REQUEST = "SEARCH_CITY_REQUEST";
export const SEARCH_CITY_SUCCESS = "SEARCH_CITY_SUCCESS";
export const SEARCH_CITY_FAILURE = "SEARCH_CITY_FAILURE";

export const SEARCH_FILTER_REQUEST = "SEARCH_FILTER_REQUEST";
export const SEARCH_FILTER_SUCCESS = "SEARCH_FILTER_SUCCESS";
export const SEARCH_FILTER_FAILURE = "SEARCH_FILTER_FAILURE";

export const SEARCH_PLACE_REQUEST = "SEARCH_PLACE_REQUEST";
export const SEARCH_PLACE_SUCCESS = "SEARCH_PLACE_SUCCESS";
export const SEARCH_PLACE_FAILURE = "SEARCH_PLACE_FAILURE";

export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORIES_FAILURE = "CATEGORIES_FAILURE";

export const CAPACITIES_REQUEST = "CAPACITIES_REQUEST";
export const CAPACITIES_SUCCESS = "CAPACITIES_SUCCESS";
export const CAPACITIES_FAILURE = "CAPACITIES_FAILURE";

export const AREAS_REQUEST = "AREAS_REQUEST";
export const AREAS_SUCCESS = "AREAS_SUCCESS";
export const AREAS_FAILURE = "AREAS_FAILURE";

export const FEATURES_REQUEST = "FEATURES_REQUEST";
export const FEATURES_SUCCESS = "FEATURES_SUCCESS";
export const FEATURES_FAILURE = "FEATURES_FAILURE";

export const RADIO_CATEGORIES = "RADIO_CATEGORIES";

export const EVENTS_REQUEST = "EVENTS_REQUEST";
export const EVENTS_SUCCESS = "EVENTS_SUCCESS";
export const EVENTS_FAILURE = "EVENTS_FAILURE";

export const CHECK_EVENTS = "CHECK_EVENTS";

export const AMENITIES_REQUEST = "AMENITIES_REQUEST";
export const AMENITIES_SUCCESS = "AMENITIES_SUCCESS";
export const AMENITIES_FAILURE = "AMENITIES_FAILURE";

export const LOCATION_REQUEST = "LOCATION_REQUEST";
export const LOCATION_SUCCESS = "LOCATION_SUCCESS";
export const LOCATION_FAILURE = "LOCATION_FAILURE";

export const CHECK_AMENITIES = "CHECK_AMENITIES";

export const SEARCH_CITY_RESET = "SEARCH_CITY_RESET";
export const GET_PEOPLE_SUCCESS = "GET_PEOPLE_SUCCESS";

export const VALIDATION_ERROR = "VALIDATION_ERROR";
export const SET_CURRENT_STEP = "SET_CURRENT_STEP";

export const GET_POPULAR_EVENT_TYPE_SUCCESS = "GET_POPULAR_EVENT_TYPE_SUCCESS";
export const SEND_USER_LOCATION_SUCCESS = "SEND_USER_LOCATION_SUCCESS";
export const GET_VENUE_listings_SUCCESS = "GET_VENUE_listings_SUCCESS";
export const GET_CRONOFY_EVENTS_SUCCESS = "GET_CRONOFY_EVENTS_SUCCESS";
export const SEND_CRONOFY_SUCCESS = "SEND_CRONOFY_SUCCESS";
