export const START_BOOKING_REQUEST = "START_BOOKING_REQUEST";
export const START_BOOKING_SUCCESS = "START_BOOKING_SUCCESS";
export const START_BOOKING_FAILURE = "START_BOOKING_FAILURE";
export const SET_BOOKING_PARAMETERS = "SET_BOOKING_PARAMETERS";
export const SET_BOOKING_ACTIVITY = "SET_BOOKING_ACTIVITY";
export const SET_BOOKING_GUESTS = "SET_BOOKING_GUESTS";
export const SET_BOOKING_DATE_TIME = "SET_BOOKING_DATE_TIME";
export const BOOKING_SUCCESS = "BOOKING_SUCCESS";
export const SET_BOOKING_CONFIRM = "SET_BOOKING_CONFIRM";
export const FAIL_BOOKING_CONFIRM = "FAIL_BOOKING_CONFIRM";
export const CONFIRM_BOOKING_SUCCESS = "CONFIRM_BOOKING_SUCCESS";
export const DATA_BOOKING_SUCCESS = "DATA_BOOKING_SUCCESS";
export const LIST_BOOKING_SUCCESS = "LIST_BOOKING_SUCCESS";
export const CHANGE_RESERVATION_SUCCESS = "CHANGE_RESERVATION_SUCCESS";
export const OVERLAP_LIST_DATA_SUCCESS = "OVERLAP_LIST_DATA_SUCCESS";
export const SUCCESS_GET_RES_ID = "SUCCESS_GET_RES_ID";
export const PAYMENT_DATA_SUCCESS = "PAYMENT_DATA_SUCCESS";
export const PAYMENT_DATA_ERROR = "PAYMENT_DATA_ERROR";
export const CURRENT_PAYMENT_SUCCESS = "CURRENT_PAYMENT_SUCCESS";
export const BALANCE_LIST_SUCCESS = "BALANCE_LIST_SUCCESS";
export const NEW_INVOICE_SUCCESS = "NEW_INVOICE_SUCCESS";
export const CANCEL_INVOICE_SUCCESS = "CANCEL_INVOICE_SUCCESS";
export const ACCEPT_INVOICE_SUCCESS = "ACCEPT_INVOICE_SUCCESS";
export const OPEN_RMODEL = "OPEN_RMODEL";
export const EXCEPTION_HOURS_START_DAY_SUCCESS =
  "EXCEPTION_HOURS_START_DAY_SUCCESS";
export const EXCEPTION_HOURS_END_DAY_SUCCESS =
  "EXCEPTION_HOURS_END_DAY_SUCCESS";
export const FAIL_EXCEPTION_DATA = "FAIL_EXCEPTION_DATA";
export const PRICE_TYPE_SUCCESS = "PRICE_TYPE_SUCCESS";
export const CHECK_PROMOCODE_SUCCESS = "CHECK_PROMOCODE_SUCCESS";
export const CHECK_PROMOCODE_FAIL = "CHECK_PROMOCODE_FAIL";

export const GET_HOURS_DAY_SUCCESS = "GET_HOURS_DAY_SUCCESS";
export const CHOSEN_NEW_SLOTS = "CHOSEN_NEW_SLOTS";
export const CHOSEN_NEW_POSITIONS = "CHOSEN_NEW_POSITIONS";
export const SET_CHOSEN_DATE = "SET_CHOSEN_DATE";
export const GET_HOURS_DAY_FAILURE = "GET_HOURS_DAY_FAILURE";
