export const ADMIN_DASHBOARD_REQUEST = "ADMIN_DASHBOARD_REQUEST";
export const ADMIN_DASHBOARD_SUCCESS = "ADMIN_DASHBOARD_SUCCESS";
export const ADMIN_DASHBOARD_FAILURE = "ADMIN_DASHBOARD_FAILURE";
export const GET_ADMIN_HOSTS_SUCCESS = "GET_ADMIN_HOSTS_SUCCESS";
export const GET_ADMIN_GUESTS_SUCCESS = "GET_ADMIN_GUESTS_SUCCESS";
export const GET_ADMIN_VENUES_SUCCESS = "GET_ADMIN_VENUES_SUCCESS";
export const GET_ADMIN_BOOKING = "GET_ADMIN_BOOKING";
export const GET_ADMIN_BOOKING_SUCCESS = "GET_ADMIN_BOOKING_SUCCESS";
export const GET_ADMIN_FILTER_VENUE_SUCCESS = "GET_ADMIN_FILTER_VENUE_SUCCESS";
export const GET_ADMIN_FILTER_USER_SUCCESS = "GET_ADMIN_FILTER_USER_SUCCESS";
export const UPDATE_USER_BY_ADMIN = "UPDATE_USER_BY_ADMIN";
export const DELETE_USER_BY_ADMIN = "DELETE_USER_BY_ADMIN";
export const GET_ADMIN_REVIEWS_SUCCESS = "GET_ADMIN_REVIEWS_SUCCESS";
export const GET_ADMIN_COUNTRY_FILTER_SUCCESS =
  "GET_ADMIN_COUNTRY_FILTER_SUCCESS";
export const GET_ADMIN_DASHBOARD_VENUES_SUCCESS =
  "GET_ADMIN_DASHBOARD_VENUES_SUCCESS";

export const GET_ADMIN_USER_SUCCESS = "GET_ADMIN_USER_SUCCESS";

export const SET_STORE_MODAL_TYPE = "SET_STORE_MODAL_TYPE";
export const GET_ADMIN_FEEDBACK_SUCCESS = "GET_ADMIN_FEEDBACK_SUCCESS";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const ADMIN_DASHBOARD_TOTAL_SUCCESS = "ADMIN_DASHBOARD_TOTAL_SUCCESS";
